### PR TITLE
Allow skipping http client init with flag

### LINKED ISSUE #15: Problems with tests
Hello!

I am not able to test as it is in the documentation, following the test guide, the application does not start:
```elixir
** (MatchError) no match of right hand side value: {:error, {:ioms, {{:shutdown, {:failed_to_start_child, Ioms.Cluster, {:undef, [{HTTPClientMock, :child_spec, [[cluster: Ioms.Cluster, url: "http://localhost:9200", username: "username", password: "password", http_client_adap
ter: HTTPClientMock]], []}, {Snap.Cluster.Supervisor, :maybe_initialize_http_client, 2, [file: 'lib/snap/supervisor.ex', line: 36]}, {Snap.Cluster.Supervisor, :init, 1, [file: 'lib/snap/supervisor.ex', line: 24]}, {:supervisor, :init, 1, [file: 'supervisor.erl', line: 330]},
 {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}, {Ioms.Application, :start, [:normal, []]}}}}
```

I have to remove the Cluster from the application, use `setup :set_mox_global` with `async: false` (not desired) and on test setup:
```elixir
setup do
  Mox.stub(HTTPClientMock, :child_spec, fn _config -> :skip end)
  Ioms.Cluster.start_link([])
end
```

Is there a better way to test?

### PR DESCRIPTION
**Pull request by feynmanliang**
The `Mox.stub` of `:child_spec` doesn't play nicely with supervised children [without additional config](https://hexdocs.pm/mox/1.0.2/Mox.html#module-multi-process-collaboration) that I don't fully comprehend.

Instead, skipping the HTTP seems to be something that's truly global and a good use of [the Application environment's global scope](https://hexdocs.pm/elixir/1.14.4/library-guidelines.html#avoid-application-configuration)

Fixes #15

### CODE REVIEW

**Comment by feynmanliang** [comment]
Hi @tomtaylor do you mind taking a look at this?

**Comment by tomtaylor** [comment]
I'll be totally honest - we don't use Mox and I've not tried to use Snap through it. Is there any way we can get some test coverage of Mox's interactions with Snap?

**Comment by feynmanliang** [comment]
Sure, I can add an integration test for it to this PR

**Comment by feynmanliang** [comment]
I added a test to exercise this; it will fail unless `skip_initialize_http_client: true` is provided.

**Comment by feynmanliang** [comment]
Hi @tomtaylor, can you take a look at the Mox integration test and let me know what you think?

**Comment by tomtaylor** [comment]
Thanks!

**Comment by tomtaylor** [comment]
I've had to revert this in #58 because the unit tests are failing intermittently. I think the way the Cluster is shutdown and then restarted doesn't quite work. You should be able to reproduce with `mix test --include integration --seed 818834`

**Comment by feynmanliang** [comment]
Thanks I’ll take a look.

**Pull request merged**
