### PR TITLE
Support http client adapters for cluster

### PR DESCRIPTION
**Pull request by jotaviobiondo**
First, congrats on this library! We are using in the company I work for and we quite like it :) 

This MR aims to provide a way for the user to setup his own HTTP client, when they don't want to use Finch. This is specially useful for testing with libs such as [mox](https://github.com/dashbitco/mox)

Besides that, I added two more things that can be useful:

- Added `mix test.all` to run all tests, including the Integration ones
- Added `mix dev` so we can enter IEx with a running dev environment: `iex -S mix dev`

This is a big change, so if you guys think that the lib should be kept simple, feel free to close this MR or create discussions :)

### CODE REVIEW

**Comment by megalithic** [comment]
@tomtaylor and team, any chance this could get merged/evaluated? I'd _love_ to get mox support?

**Comment by gabrielpra1** [comment]
I'm also interested in this one! We've been running this fork for a while now and haven't had any problems with it 🙂

**Comment by tomtaylor** [comment]
Thanks @megalithic, on first glance this looks very thorough, but let me have a proper look through this and review. In the mean time, are you able to resolve the merge conflicts?

**Comment by jotaviobiondo** [comment]
Hey! @tomtaylor thanks for taking the time to review it ❤️  just solved the conflicts :) 

and thanks for the support @megalithic and @gabrielpra1! ❤️

**Comment by tomtaylor** [comment]
Thanks, released in 0.6!

**Pull request merged**
